In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/iggym/Documents/URacing Team/TelemetryData_10230136787177318441/TelemetryData_10230136787177318441.csv", header=0, low_memory=False)

In [8]:
df.tail(1)

,sessionTime,frameIdentifier,pilot_index,worldPositionX,worldPositionY,worldPositionZ,worldVelocityX,worldVelocityY,worldVelocityZ,worldForwardDirX,...,ersDeployedThisLap,carPosition,currentLapTime,currentLapNum,lapDistance,totalDistance,pitStatus,sector,driverStatus,resultStatus
1180639,3092.51074,65176,19,-805.82227,0.12108,-1011.11804,73.12712,0.38642,10.47222,32432,...,3791229.25,1,79.9232,36,4523.29688,162909.1875,NaN,2,on track,active

In [9]:
print(3092.51074/60)

51.54184566666667

In [17]:
pilot_10 = df[df.pilot_index==10]

In [18]:
pilot_10.shape

(59032, 56)

In [19]:
pilot_10.sessionTime.max()

3092.51074

In [20]:
pilot_10.tail(1)

,sessionTime,frameIdentifier,pilot_index,worldPositionX,worldPositionY,worldPositionZ,worldVelocityX,worldVelocityY,worldVelocityZ,worldForwardDirX,...,ersDeployedThisLap,carPosition,currentLapTime,currentLapNum,lapDistance,totalDistance,pitStatus,sector,driverStatus,resultStatus
1180630,3092.51074,65176,10,86.8092,2.06245,-33.04312,9.45375,-0.27915,-46.98124,6461,...,1618968.875,5,43.40771,36,2510.8125,160896.70312,NaN,1,on track,active

In [21]:
pilot_10.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59032 entries, 10 to 1180630
Data columns (total 56 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sessionTime              59032 non-null  float64
 1   frameIdentifier          59032 non-null  int64
 2   pilot_index              59032 non-null  int64
 3   worldPositionX           59032 non-null  float64
 4   worldPositionY           59032 non-null  float64
 5   worldPositionZ           59032 non-null  float64
 6   worldVelocityX           59032 non-null  float64
 7   worldVelocityY           59032 non-null  float64
 8   worldVelocityZ           59032 non-null  float64
 9   worldForwardDirX         59032 non-null  int64
 10  worldForwardDirY         59032 non-null  int64
 11  worldForwardDirZ         59032 non-null  int64
 12  worldRightDirX           59032 non-null  int64
 13  worldRightDirY           59032 non-null  int64
 14  worldRightDirZ           59032 non-null  int64
 15  gForceLateral            59032 non-null  float64
 16  gForceLongitudinal       59032 non-null  float64
 17  gForceVertical           59032 non-null  float64
 18  yaw                      59032 non-null  float64
 19  pitch                    59032 non-null  float64
 20  roll                     59032 non-null  float64
 21  speed                    59032 non-null  int64
 22  throttle                 59032 non-null  float64
 23  steer                    59032 non-null  float64
 24  brake                    59032 non-null  float64
 25  clutch                   59032 non-null  int64
 26  gear                     59032 non-null  int64
 27  engineRPM                59032 non-null  int64
 28  drs                      59032 non-null  int64
 29  brakesTemperature        59032 non-null  object
 30  tyresSurfaceTemperature  59032 non-null  object
 31  tyresInnerTemperature    59032 non-null  object
 32  engineTemperature        59032 non-null  int64
 33  tyresPressure            59032 non-null  object
 34  surfaceType              59032 non-null  object
 35  fuelMix                  59029 non-null  float64
 36  pitLimiterStatus         59029 non-null  float64
 37  fuelInTank               59029 non-null  float64
 38  fuelRemainingLaps        59029 non-null  float64
 39  tyresWear                59029 non-null  object
 40  actualTyreCompound       59029 non-null  object
 41  tyresDamage              59029 non-null  object
 42  ersStoreEnergy           59029 non-null  float64
 43  ersDeployMode            59029 non-null  float64
 44  ersHarvestedThisLapMGUK  59029 non-null  float64
 45  ersHarvestedThisLapMGUH  59029 non-null  float64
 46  ersDeployedThisLap       59029 non-null  float64
 47  carPosition              59032 non-null  int64
 48  currentLapTime           59032 non-null  float64
 49  currentLapNum            59032 non-null  int64
 50  lapDistance              59032 non-null  float64
 51  totalDistance            59032 non-null  float64
 52  pitStatus                870 non-null    object
 53  sector                   59032 non-null  int64
 54  driverStatus             59032 non-null  object
 55  resultStatus             59032 non-null  object
dtypes: float64(28), int64(17), object(11)
memory usage: 25.7+ MB

In [10]:
pilot_10.memory_usage(index=False)

Index                      472256
sessionTime                472256
frameIdentifier            472256
pilot_index                472256
worldPositionX             472256
worldPositionY             472256
worldPositionZ             472256
worldVelocityX             472256
worldVelocityY             472256
worldVelocityZ             472256
worldForwardDirX           472256
worldForwardDirY           472256
worldForwardDirZ           472256
worldRightDirX             472256
worldRightDirY             472256
worldRightDirZ             472256
gForceLateral              472256
gForceLongitudinal         472256
gForceVertical             472256
yaw                        472256
pitch                      472256
roll                       472256
speed                      472256
throttle                   472256
steer                      472256
brake                      472256
clutch                     472256
gear                       472256
engineRPM                  472256
drs                        472256
brakesTemperature          472256
tyresSurfaceTemperature    472256
tyresInnerTemperature      472256
engineTemperature          472256
tyresPressure              472256
surfaceType                472256
fuelMix                    472256
pitLimiterStatus           472256
fuelInTank                 472256
fuelRemainingLaps          472256
tyresWear                  472256
actualTyreCompound         472256
tyresDamage                472256
ersStoreEnergy             472256
ersDeployMode              472256
ersHarvestedThisLapMGUK    472256
ersHarvestedThisLapMGUH    472256
ersDeployedThisLap         472256
carPosition                472256
currentLapTime             472256
currentLapNum              472256
lapDistance                472256
totalDistance              472256
pitStatus                  472256
sector                     472256
driverStatus               472256
resultStatus               472256
dtype: int64

In [2]:
df2 = pd.read_csv("data/processed_data.csv", header=0)

In [4]:
df2.tail()

,sessiontime,pilot_index,worldpositionz,speed,throttle,steer,brake,gear,enginerpm,enginetemperature,fuelintank,currentlaptime,currentlapnum,lapdistance,totaldistance,worldpositionx,worldpositiony,lat,lon
59027,3092.30054,10,-23.49174,163,0.70432,0.00123,0.0,4,10048,89,1.30474,43.19836,36,2501.07812,160886.96875,84.89368,2.12082,-33.460724,-70.673893
59028,3092.35059,10,-25.72190,165,0.78331,-0.00000,0.0,4,10177,89,1.30314,43.24833,36,2503.35938,160889.25000,85.33980,2.10683,-33.460724,-70.673902
59029,3092.41064,10,-28.42525,167,0.87765,0.00123,0.0,4,10355,89,1.30116,43.30801,36,2506.10938,160892.00000,85.88155,2.09015,-33.460724,-70.673912
59030,3092.46069,10,-30.71815,169,0.95651,0.00302,0.0,4,10525,89,1.29947,43.35789,36,2508.43750,160894.32812,86.34175,2.07632,-33.460724,-70.673921
59031,3092.51074,10,-33.04312,172,1.00000,0.00349,0.0,4,10701,89,1.29775,43.40771,36,2510.81250,160896.70312,86.80920,2.06245,-33.460724,-70.673931

In [8]:
lap_6 = df2[df2.currentlapnum == 6]

In [12]:
lap_6.to_csv("data/lap_6.csv", index=False)

In [11]:
lap_6.head()

,sessiontime,pilot_index,worldpositionz,speed,throttle,steer,brake,gear,enginerpm,enginetemperature,fuelintank,currentlaptime,currentlapnum,lapdistance,totaldistance,worldpositionx,worldpositiony,lat,lon
9222,482.48828,10,-1017.67377,257,1.00000,0.00174,0.0,6,11802,89,50.97413,0.01955,6,1.93555,22628.49023,-800.91882,0.13666,-33.460741,-70.656427
9223,482.53799,10,-1017.15240,257,0.97932,0.00578,0.0,7,11058,89,50.97377,0.06906,6,5.50781,22632.06250,-797.40717,0.15839,-33.460741,-70.656496
9224,482.58841,10,-1016.61981,258,1.00000,0.00508,0.0,7,10456,89,50.97199,0.11937,6,9.14648,22635.70117,-793.83197,0.18002,-33.460741,-70.656567
9225,482.63965,10,-1016.07434,259,1.00000,0.00000,0.0,7,10448,89,50.97024,0.17046,6,12.86133,22639.41602,-790.18250,0.20183,-33.460741,-70.656639
9226,482.69040,10,-1015.52911,260,1.00000,-0.00276,0.0,7,10489,89,50.96849,0.22141,6,16.55664,22643.11133,-786.55029,0.22382,-33.460741,-70.656710